- hosts: all
  gather_facts: yes
  vars:
    user: joe
    package: vsftpd
  tasks:
    - name: add a user "{{ user }}"
      user:
       name: "{{ user }}"

    - name: Remove package httpd
      package:
        name: "{{ package }}"
        state: latest
      register: result
