- hosts: all
  gather_facts: yes
  vars:
    user: joe
    package: httpd
  tasks:
    - name: add a user "{{ user }}"
      user:
       name: "{{ user }}"

    - name: Remove package "{{ package }}"
      package:
        name: "{{ package }}"
        state: latest
      register: result
